[meta] 
name = "salt"
version = "v0.2.3"
description = "Fast and simple task management from the CLI."
homepage = "https://github.com/Milo123459/salt"
license = "mit"
maintainers = []

[meta.github]
owner = "Milo123459"
repo = "salt"
rev = "v0.2.3"
sha256 = "1d17lxz8kfmzybbpkz1797qkq1h4jwkbgwh2yrwrymraql8rfy42"

[meta.cargoPackage]
sha256 = "1615z6agnbfwxv0wn9xfkh8yh5waxpygv00m6m71ywzr49y0n6h6"